services:
  radarr:
    image: lscr.io/linuxserver/radarr:6.0.4
    container_name: radarr
    environment:
      - PUID=501
      - PGID=20
      - TZ=Europe/Madrid
    volumes:
      - ./config:/config
      - /Users/lukas/mnt/gdrive/media:/data
      - ../qbittorrent/downloads:/downloads
    restart: unless-stopped
    network_mode: container:gluetun

volumes:
   data:
     name: media-tube-data
