services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./config/peer2.conf:/gluetun/wireguard/wg0.conf
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
      - 5055:5055
      - 9696:9696
      - 8989:8989
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      # - DOT=${DOT}
      # - DNS_ADDRESS=${DNS_ADDRESS}
    networks:
      - vpn

networks:
  vpn:
    name: "vpn"
